server:
  port: 8081

spring:
  application:
     name: gamelove
  datasource:
    url: jdbc:h2:file:./data/gamelove
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

api:
  key: game-api-key
  secret: abcdegh
